import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import JSZip from "jszip";

// Generates JSX code string for a single component
function generateComponentJsx(type: string, props: any): string {
  const propsStr = JSON.stringify(props, null, 4)
    .replace(/"([^"]+)":/g, "$1:") // remove quotes from keys
    .replace(/"/g, "'");           // double quotes → single quotes

  return `<${type}\n  {...${propsStr}}\n/>`;
}

// Generates the App.jsx content
function generateAppJsx(components: any[], projectName: string): string {
  const imports = [...new Set(components.map((c) => c.type))]
    .map((type) => `import { ${type} } from './components/${type}';`)
    .join("\n");

  const sectionJsx = components
    .map((c) => `      ${generateComponentJsx(c.type, c.props || {})}`)
    .join("\n\n");

  return `import React from 'react';
${imports}

// Generated by AI Landing Page Builder
// Project: ${projectName}

export default function LandingPage() {
  return (
    <main>
${sectionJsx}
    </main>
  );
}
`;
}

// Generates a simple stub component file for each type
function generateStubComponent(type: string): string {
  return `import React from 'react';

// ${type} component — edit props and styles as needed
export function ${type}(props) {
  // All props are passed directly from the page data
  // Refer to your AI Landing Page Builder project for the full implementation
  console.warn('[${type}] This is a stub. Replace with your actual component implementation.');
  return (
    <section data-component="${type}" style={{ padding: '4rem 2rem' }}>
      <pre style={{ fontSize: '12px', opacity: 0.5 }}>
        {JSON.stringify(props, null, 2)}
      </pre>
    </section>
  );
}
`;
}

// Generates package.json for the exported project
function generatePackageJson(projectName: string): string {
  const safeName = projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return JSON.stringify({
    name: safeName,
    version: "1.0.0",
    description: `Landing page generated by AI Landing Page Builder`,
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.3.1",
      "react-dom": "^18.3.1",
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.3.4",
      vite: "^6.0.7",
      "@tailwindcss/vite": "^4.0.0",
      tailwindcss: "^4.0.0",
    },
  }, null, 2);
}

// Generates the entry index.html for Vite
function generateIndexHtml(projectName: string): string {
  return `<!DOCTYPE html>
<html lang="id">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;
}

// Generates src/main.jsx
function generateMainJsx(): string {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import LandingPage from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <LandingPage />
  </React.StrictMode>
);
`;
}

// Generates src/index.css with Tailwind v4 import
function generateIndexCss(): string {
  return `@import "tailwindcss";

* {
  box-sizing: border-box;
}

body {
  font-family: 'Inter', sans-serif;
  margin: 0;
}
`;
}

// Generates vite.config.js
function generateViteConfig(): string {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
  ],
});
`;
}

function generateReadme(projectName: string, components: any[]): string {
  const sections = [...new Set(components.map((c) => c.type))].join(", ");
  return `# ${projectName}

Generated by **AI Landing Page Builder**.

## Sections
${sections}

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Replace stub components in \`src/components/\` with your actual implementations.
   - The full component source is available in your AI Landing Page Builder project.
   - Each component receives props exactly as shown in \`src/App.jsx\`.

3. Run the dev server:
\`\`\`bash
npm run dev
\`\`\`

## Project Structure

\`\`\`
├── index.html
├── vite.config.js
├── package.json
└── src/
    ├── main.jsx         ← Entry point
    ├── App.jsx          ← Assembled landing page
    ├── index.css        ← Tailwind CSS
    └── components/      ← Stub components (replace with real ones)
        ${[...new Set(components.map((c) => c.type))].map((t) => `├── ${t}.jsx`).join("\n        ")}
\`\`\`

## Page Data (JSON)

\`\`\`json
${JSON.stringify(components, null, 2)}
\`\`\`
`;
}

export async function GET(req: NextRequest) {
  try {
    const projectId = req.nextUrl.searchParams.get("id");
    if (!projectId) return NextResponse.json({ error: "Missing id" }, { status: 400 });

    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: { landingPage: true },
    });

    if (!project || !project.landingPage) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const components: any[] = (project.landingPage.content as any)?.components || [];
    const projectName = project.name || "landing-page";

    // Build ZIP
    const zip = new JSZip();

    // Root files
    zip.file("index.html", generateIndexHtml(projectName));
    zip.file("package.json", generatePackageJson(projectName));
    zip.file("vite.config.js", generateViteConfig());
    zip.file("README.md", generateReadme(projectName, components));

    // src/
    const src = zip.folder("src")!;
    src.file("main.jsx", generateMainJsx());
    src.file("App.jsx", generateAppJsx(components, projectName));
    src.file("index.css", generateIndexCss());

    // src/components/ — stub for each unique section type
    const componentsFolder = src.folder("components")!;
    const uniqueTypes = [...new Set(components.map((c) => c.type))];
    for (const type of uniqueTypes) {
      componentsFolder.file(`${type}.jsx`, generateStubComponent(type));
    }

    // Also save the raw page data as JSON
    src.file("page-data.json", JSON.stringify(components, null, 2));

    const zipBuffer = await zip.generateAsync({ type: "arraybuffer", compression: "DEFLATE" });
    const safeName = projectName.replace(/[^a-z0-9]/gi, "-").toLowerCase();

    return new NextResponse(zipBuffer as unknown as BodyInit, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${safeName}.zip"`,
      },
    });
  } catch (err) {
    console.error("[export/jsx]", err);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
