import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import JSZip from "jszip";

// Generates JSX code string for a single component
function generateComponentJsx(type: string, props: any): string {
  const propsStr = JSON.stringify(props, null, 4)
    .replace(/"([^"]+)":/g, "$1:") // remove quotes from keys
    .replace(/"/g, "'");           // double quotes → single quotes

  return `<${type}\n  {...${propsStr}}\n/>`;
}

// Generates the App.jsx content
function generateAppJsx(components: any[], projectName: string): string {
  const imports = [...new Set(components.map((c) => c.type))]
    .map((type) => `import { ${type} } from './components/${type}';`)
    .join("\n");

  const sectionJsx = components
    .map((c) => `      ${generateComponentJsx(c.type, c.props || {})}`)
    .join("\n\n");

  return `import React from 'react';
${imports}

// Generated by AI Landing Page Builder
// Project: ${projectName}

export default function LandingPage() {
  return (
    <main>
${sectionJsx}
    </main>
  );
}
`;
}

// Generates full styled React + Tailwind CSS component implementation for each type
function generateStubComponent(type: string): string {
  switch (type) {
    case "Navbar":
      return `import React from 'react';

export function Navbar({ logoText = 'Company', links = [], ctaText = 'Get Started', bgColor, textColor, accentColor }) {
  const isDark = bgColor && bgColor.toLowerCase() !== '#ffffff';
  const buttonBg = accentColor || (isDark ? '#ffffff' : '#111827');
  const buttonTextColor = accentColor ? '#ffffff' : (isDark ? '#111827' : '#ffffff');

  return (
    <header className="w-full relative shadow-sm" style={{ backgroundColor: bgColor || '#111827', color: textColor || '#ffffff' }}>
      <nav className="mx-auto flex max-w-7xl items-center justify-between p-4 sm:p-6 lg:px-8">
        <div className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-lg flex items-center justify-center font-bold text-white text-lg shadow-sm" style={{ backgroundColor: accentColor || '#3b82f6' }}>
            {logoText.charAt(0)}
          </div>
          <span className="font-bold text-lg sm:text-xl tracking-tight">{logoText}</span>
        </div>
        <div className="flex items-center gap-x-6">
          {(links || []).map((item, idx) => (
            <a key={idx} href={item.url || '#'} className="text-xs sm:text-sm font-semibold hover:opacity-80 transition-opacity">
              {item.label}
            </a>
          ))}
        </div>
        {ctaText && (
          <a href="#" className="hidden sm:inline-block rounded-full px-5 py-2 text-xs sm:text-sm font-bold shadow-md transition-all hover:scale-105" style={{ backgroundColor: buttonBg, color: buttonTextColor }}>
            {ctaText}
          </a>
        )}
      </nav>
    </header>
  );
}`;

    case "Hero":
      return `import React from 'react';

export function Hero({ title, subtitle, badgeText, primaryCta, secondaryCta, bgColor, textColor, accentColor, variant = 'centered', layout = 'center' }) {
  const isRight = layout === 'right';
  const isLeft = layout === 'left';
  const alignClass = isRight ? 'text-right items-end' : isLeft ? 'text-left items-start' : 'text-center items-center';

  return (
    <section className="relative overflow-hidden py-24 sm:py-32 px-6" style={{ backgroundColor: bgColor || '#0f172a', color: textColor || '#ffffff' }}>
      <div className={\`mx-auto max-w-5xl flex flex-col \${alignClass} space-y-6 relative z-10\`}>
        {badgeText && (
          <span className="inline-block px-3.5 py-1 rounded-full text-xs font-mono font-bold tracking-wide uppercase shadow-sm" style={{ backgroundColor: accentColor || '#3b82f6', color: '#ffffff' }}>
            {badgeText}
          </span>
        )}
        <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight leading-tight max-w-3xl">
          {title || 'Build Better Products Fast'}
        </h1>
        <p className="text-lg sm:text-xl opacity-80 max-w-2xl leading-relaxed">
          {subtitle || 'Supercharge your workflow with our modern components and flexible layout design system.'}
        </p>
        <div className={\`flex flex-wrap gap-4 pt-4 \${isRight ? 'justify-end' : isLeft ? 'justify-start' : 'justify-center'}\`}>
          {primaryCta && (
            <a href={primaryCta.url || '#'} className="px-6 py-3.5 rounded-xl font-bold text-sm shadow-lg transition-all hover:scale-105" style={{ backgroundColor: accentColor || '#3b82f6', color: '#ffffff' }}>
              {primaryCta.label || 'Get Started'}
            </a>
          )}
          {secondaryCta && (
            <a href={secondaryCta.url || '#'} className="px-6 py-3.5 rounded-xl font-bold text-sm border border-white/20 hover:bg-white/10 transition-all">
              {secondaryCta.label || 'Learn More'}
            </a>
          )}
        </div>
      </div>
    </section>
  );
}`;

    case "Features":
      return `import React from 'react';

export function Features({ title, subtitle, items = [], bgColor, textColor, accentColor }) {
  return (
    <section className="py-20 px-6" style={{ backgroundColor: bgColor || '#f8fafc', color: textColor || '#0f172a' }}>
      <div className="mx-auto max-w-6xl space-y-12">
        <div className="text-center space-y-3 max-w-3xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">{title || 'Our Features'}</h2>
          {subtitle && <p className="text-base opacity-75">{subtitle}</p>}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {(items || []).map((item, idx) => (
            <div key={idx} className="p-6 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm space-y-3">
              <div className="w-10 h-10 rounded-xl flex items-center justify-center font-bold text-white text-lg" style={{ backgroundColor: accentColor || '#3b82f6' }}>
                {item.icon || '✨'}
              </div>
              <h3 className="text-lg font-bold">{item.title}</h3>
              <p className="text-sm opacity-80 leading-relaxed">{item.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}`;

    case "Pricing":
      return `import React from 'react';

export function Pricing({ title, subtitle, plans = [], bgColor, textColor, accentColor }) {
  return (
    <section className="py-20 px-6" style={{ backgroundColor: bgColor || '#ffffff', color: textColor || '#0f172a' }}>
      <div className="mx-auto max-w-6xl space-y-12">
        <div className="text-center space-y-3 max-w-3xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">{title || 'Simple Pricing'}</h2>
          {subtitle && <p className="text-base opacity-75">{subtitle}</p>}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {(plans || []).map((plan, idx) => (
            <div key={idx} className={\`p-8 rounded-3xl border \${plan.isPopular ? 'border-2 shadow-xl scale-105' : 'border-zinc-200 shadow-sm'} space-y-6 flex flex-col justify-between\`} style={{ borderColor: plan.isPopular ? (accentColor || '#3b82f6') : undefined }}>
              <div className="space-y-4">
                {plan.isPopular && (
                  <span className="px-3 py-1 rounded-full text-xs font-bold text-white uppercase tracking-wider inline-block" style={{ backgroundColor: accentColor || '#3b82f6' }}>
                    Most Popular
                  </span>
                )}
                <h3 className="text-xl font-bold">{plan.name}</h3>
                <div className="text-3xl font-extrabold">{plan.price}</div>
                <p className="text-xs opacity-75">{plan.description}</p>
                <ul className="space-y-2 text-xs pt-4 border-t border-zinc-200">
                  {(plan.features || []).map((feat, fIdx) => (
                    <li key={fIdx} className="flex items-center gap-2">✓ {feat}</li>
                  ))}
                </ul>
              </div>
              <button className="w-full py-3 rounded-xl font-bold text-xs text-white shadow-md transition-all hover:scale-105" style={{ backgroundColor: accentColor || '#3b82f6' }}>
                {plan.ctaText || 'Choose Plan'}
              </button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}`;

    case "Testimonials":
      return `import React from 'react';

export function Testimonials({ title, subtitle, items = [], bgColor, textColor, variant = 'grid' }) {
  const safeItems = Array.isArray(items) ? items : [];

  if (variant === 'marquee') {
    const doubled = [...safeItems, ...safeItems];
    return (
      <section className="py-16 sm:py-24 overflow-hidden" style={{ backgroundColor: bgColor || '#0f172a', color: textColor || '#ffffff' }}>
        <div className="mx-auto max-w-7xl px-6 mb-12 text-center">
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">{title || 'Trusted by Industry Leaders'}</h2>
          {subtitle && <p className="text-base opacity-75 mt-2">{subtitle}</p>}
        </div>
        <div className="relative flex overflow-hidden mb-6">
          <div className="flex gap-6 animate-marquee-left whitespace-nowrap">
            {doubled.map((t, i) => (
              <div key={i} className="inline-flex flex-col min-w-[300px] sm:min-w-[350px] p-6 rounded-2xl bg-white/10 backdrop-blur-md border border-white/15 shrink-0">
                <p className="text-xs sm:text-sm italic leading-relaxed whitespace-normal">"{t.quote}"</p>
                <div className="mt-4 flex items-center gap-3 pt-3 border-t border-white/10">
                  <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center text-xs font-bold shrink-0">
                    {t.author ? t.author.charAt(0) : 'U'}
                  </div>
                  <div>
                    <span className="text-xs font-bold">{t.author}</span>
                    {t.role && <span className="text-[10px] opacity-75 ml-1.5">· {t.role}</span>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="relative flex overflow-hidden">
          <div className="flex gap-6 animate-marquee-right whitespace-nowrap">
            {[...doubled].reverse().map((t, i) => (
              <div key={i} className="inline-flex flex-col min-w-[300px] sm:min-w-[350px] p-6 rounded-2xl bg-white/10 backdrop-blur-md border border-white/15 shrink-0">
                <p className="text-xs sm:text-sm italic leading-relaxed whitespace-normal">"{t.quote}"</p>
                <div className="mt-4 flex items-center gap-3 pt-3 border-t border-white/10">
                  <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center text-xs font-bold shrink-0">
                    {t.author ? t.author.charAt(0) : 'U'}
                  </div>
                  <div>
                    <span className="text-xs font-bold">{t.author}</span>
                    {t.role && <span className="text-[10px] opacity-75 ml-1.5">· {t.role}</span>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  if (variant === 'masonry') {
    return (
      <section className="py-20 px-6" style={{ backgroundColor: bgColor || '#0f172a', color: textColor || '#ffffff' }}>
        <div className="mx-auto max-w-6xl space-y-12">
          <div className="text-center space-y-3 max-w-3xl mx-auto">
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">{title || 'Trusted by Industry Leaders'}</h2>
            {subtitle && <p className="text-base opacity-75">{subtitle}</p>}
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {safeItems.map((item, idx) => (
              <figure key={idx} className={\`p-8 rounded-3xl bg-white/10 backdrop-blur-md border border-white/15 shadow-sm space-y-4 \${idx === 0 ? 'sm:col-span-2' : ''}\`}>
                <blockquote className="text-lg leading-relaxed font-medium">"{item.quote}"</blockquote>
                <figcaption className="pt-4 flex items-center gap-3 border-t border-white/10">
                  <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center font-bold text-sm">
                    {item.author ? item.author.charAt(0) : 'U'}
                  </div>
                  <div>
                    <div className="font-bold text-sm">{item.author}</div>
                    {item.role && <div className="text-xs opacity-75">{item.role}</div>}
                  </div>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>
    );
  }

  // Default Grid
  return (
    <section className="py-20 px-6" style={{ backgroundColor: bgColor || '#0f172a', color: textColor || '#ffffff' }}>
      <div className="mx-auto max-w-6xl space-y-12">
        <div className="text-center space-y-3 max-w-3xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">{title || 'Trusted by Industry Leaders'}</h2>
          {subtitle && <p className="text-base opacity-75">{subtitle}</p>}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {safeItems.map((item, idx) => (
            <div key={idx} className="p-6 rounded-2xl bg-white/10 backdrop-blur-md border border-white/15 shadow-sm space-y-4 flex flex-col justify-between">
              <p className="text-sm italic leading-relaxed">"{item.quote}"</p>
              <div className="pt-3 border-t border-white/10 flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center font-bold text-xs">
                  {item.author ? item.author.charAt(0) : 'U'}
                </div>
                <div>
                  <div className="font-bold text-sm">{item.author}</div>
                  <div className="text-xs opacity-70">{item.role}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}`;

    case "FAQ":
      return `import React from 'react';

export function FAQ({ title, subtitle, items = [], bgColor, textColor }) {
  return (
    <section className="py-20 px-6" style={{ backgroundColor: bgColor || '#f8fafc', color: textColor || '#0f172a' }}>
      <div className="mx-auto max-w-4xl space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-3xl font-extrabold">{title || 'Frequently Asked Questions'}</h2>
          {subtitle && <p className="text-sm opacity-75">{subtitle}</p>}
        </div>
        <div className="space-y-4">
          {(items || []).map((item, idx) => (
            <details key={idx} className="p-5 rounded-2xl bg-white border border-zinc-200 shadow-sm cursor-pointer group">
              <summary className="font-bold text-sm flex justify-between items-center list-none">
                {item.question}
                <span className="text-blue-500 font-mono group-open:rotate-45 transition-transform">+</span>
              </summary>
              <p className="text-xs opacity-80 pt-3 leading-relaxed">{item.answer}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}`;

    case "CTA":
      return `import React from 'react';

export function CTA({ title, subtitle, buttonText, buttonUrl, bgColor, textColor, accentColor }) {
  return (
    <section className="py-20 px-6 text-center" style={{ backgroundColor: bgColor || '#3b82f6', color: textColor || '#ffffff' }}>
      <div className="mx-auto max-w-4xl space-y-6 p-10 rounded-3xl bg-white/10 backdrop-blur-md border border-white/20 shadow-xl">
        <h2 className="text-3xl sm:text-5xl font-extrabold tracking-tight">{title || 'Ready to Get Started?'}</h2>
        {subtitle && <p className="text-base opacity-90 max-w-xl mx-auto">{subtitle}</p>}
        {buttonText && (
          <a href={buttonUrl || '#'} className="inline-block px-8 py-3.5 rounded-full font-bold text-sm shadow-lg transition-all hover:scale-105" style={{ backgroundColor: accentColor || '#ffffff', color: '#0f172a' }}>
            {buttonText}
          </a>
        )}
      </div>
    </section>
  );
}`;

    case "Footer":
      return `import React from 'react';

export function Footer({ companyName = 'Company', text, links = [], bgColor, textColor }) {
  return (
    <footer className="py-12 px-6 border-t border-white/10" style={{ backgroundColor: bgColor || '#0f172a', color: textColor || '#94a3b8' }}>
      <div className="mx-auto max-w-7xl flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="space-y-1 text-center md:text-left">
          <div className="font-bold text-white text-base">{companyName}</div>
          <p className="text-xs opacity-75">{text || \`© \${new Date().getFullYear()} \${companyName}. All rights reserved.\`}</p>
        </div>
        <div className="flex gap-6 text-xs font-semibold">
          {(links || []).map((l, idx) => (
            <a key={idx} href={l.url || '#'} className="hover:text-white transition-colors">{l.label}</a>
          ))}
        </div>
      </div>
    </footer>
  );
}`;

    default:
      return `import React from 'react';

export function ${type}(props) {
  return (
    <section className="py-12 px-6 text-center bg-zinc-900 text-white">
      <h3 className="font-bold text-lg">${type}</h3>
    </section>
  );
}`;
  }
}

// Generates package.json for the exported project
function generatePackageJson(projectName: string): string {
  const safeName = projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return JSON.stringify({
    name: safeName,
    version: "1.0.0",
    description: `Landing page generated by AI Landing Page Builder`,
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.3.1",
      "react-dom": "^18.3.1",
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.3.4",
      vite: "^6.0.7",
      "@tailwindcss/vite": "^4.0.0",
      tailwindcss: "^4.0.0",
    },
  }, null, 2);
}

// Generates the entry index.html for Vite
function generateIndexHtml(projectName: string): string {
  return `<!DOCTYPE html>
<html lang="id">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;
}

// Generates src/main.jsx
function generateMainJsx(): string {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import LandingPage from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <LandingPage />
  </React.StrictMode>
);
`;
}

// Generates src/index.css with Tailwind v4 import & Marquee Keyframe Animations
function generateIndexCss(): string {
  return `@import "tailwindcss";

@keyframes marquee-left {
  0% { transform: translateX(0%); }
  100% { transform: translateX(-50%); }
}

@keyframes marquee-right {
  0% { transform: translateX(-50%); }
  100% { transform: translateX(0%); }
}

.animate-marquee-left {
  display: flex;
  width: max-content;
  animation: marquee-left 25s linear infinite;
}

.animate-marquee-right {
  display: flex;
  width: max-content;
  animation: marquee-right 25s linear infinite;
}

.animate-marquee-left:hover, .animate-marquee-right:hover {
  animation-play-state: paused;
}

* {
  box-sizing: border-box;
}

body {
  font-family: 'Inter', sans-serif;
  margin: 0;
}
`;
}

// Generates vite.config.js
function generateViteConfig(): string {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
  ],
});
`;
}

function generateReadme(projectName: string, components: any[]): string {
  const sections = [...new Set(components.map((c) => c.type))].join(", ");
  return `# ${projectName}

Generated by **AI Landing Page Builder**.

## Sections
${sections}

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Replace stub components in \`src/components/\` with your actual implementations.
   - The full component source is available in your AI Landing Page Builder project.
   - Each component receives props exactly as shown in \`src/App.jsx\`.

3. Run the dev server:
\`\`\`bash
npm run dev
\`\`\`

## Project Structure

\`\`\`
├── index.html
├── vite.config.js
├── package.json
└── src/
    ├── main.jsx         ← Entry point
    ├── App.jsx          ← Assembled landing page
    ├── index.css        ← Tailwind CSS
    └── components/      ← Stub components (replace with real ones)
        ${[...new Set(components.map((c) => c.type))].map((t) => `├── ${t}.jsx`).join("\n        ")}
\`\`\`

## Page Data (JSON)

\`\`\`json
${JSON.stringify(components, null, 2)}
\`\`\`
`;
}

export async function GET(req: NextRequest) {
  try {
    const projectId = req.nextUrl.searchParams.get("id");
    if (!projectId) return NextResponse.json({ error: "Missing id" }, { status: 400 });

    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: { landingPage: true },
    });

    if (!project || !project.landingPage) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const components: any[] = (project.landingPage.content as any)?.components || [];
    const projectName = project.name || "landing-page";

    // Build ZIP
    const zip = new JSZip();

    // Root files
    zip.file("index.html", generateIndexHtml(projectName));
    zip.file("package.json", generatePackageJson(projectName));
    zip.file("vite.config.js", generateViteConfig());
    zip.file("README.md", generateReadme(projectName, components));

    // src/
    const src = zip.folder("src")!;
    src.file("main.jsx", generateMainJsx());
    src.file("App.jsx", generateAppJsx(components, projectName));
    src.file("index.css", generateIndexCss());

    // src/components/ — stub for each unique section type
    const componentsFolder = src.folder("components")!;
    const uniqueTypes = [...new Set(components.map((c) => c.type))];
    for (const type of uniqueTypes) {
      componentsFolder.file(`${type}.jsx`, generateStubComponent(type));
    }

    // Also save the raw page data as JSON
    src.file("page-data.json", JSON.stringify(components, null, 2));

    const zipBuffer = await zip.generateAsync({ type: "arraybuffer", compression: "DEFLATE" });
    const safeName = projectName.replace(/[^a-z0-9]/gi, "-").toLowerCase();

    return new NextResponse(zipBuffer as unknown as BodyInit, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${safeName}.zip"`,
      },
    });
  } catch (err) {
    console.error("[export/jsx]", err);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
